/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MaturacaoRouteImport } from './routes/maturacao'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as MixRouteImport } from './routes/mix'
import { Route as PracasRouteImport } from './routes/pracas'
import { Route as QualidadeRouteImport } from './routes/qualidade'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as ExternosIndexRouteImport } from './routes/externos/index'
import { Route as ExternosAbastecimentoRouteImport } from './routes/externos/abastecimento'
import { Route as ExternosAderenciaRouteImport } from './routes/externos/aderencia'
import { Route as ExternosMercadoRouteImport } from './routes/externos/mercado'
import { Route as ExternosOperacaoRouteImport } from './routes/externos/operacao'
import { Route as ExternosRiscoRouteImport } from './routes/externos/risco'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MaturacaoRoute = MaturacaoRouteImport.update({
  id: '/maturacao',
  path: '/maturacao',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const MixRoute = MixRouteImport.update({
  id: '/mix',
  path: '/mix',
  getParentRoute: () => rootRouteImport,
} as any)
const PracasRoute = PracasRouteImport.update({
  id: '/pracas',
  path: '/pracas',
  getParentRoute: () => rootRouteImport,
} as any)
const QualidadeRoute = QualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternosIndexRoute = ExternosIndexRouteImport.update({
  id: '/externos/',
  path: '/externos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternosAbastecimentoRoute = ExternosAbastecimentoRouteImport.update({
  id: '/externos/abastecimento',
  path: '/externos/abastecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternosAderenciaRoute = ExternosAderenciaRouteImport.update({
  id: '/externos/aderencia',
  path: '/externos/aderencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternosMercadoRoute = ExternosMercadoRouteImport.update({
  id: '/externos/mercado',
  path: '/externos/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternosOperacaoRoute = ExternosOperacaoRouteImport.update({
  id: '/externos/operacao',
  path: '/externos/operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternosRiscoRoute = ExternosRiscoRouteImport.update({
  id: '/externos/risco',
  path: '/externos/risco',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/financeiro': typeof FinanceiroRoute
  '/mapa': typeof MapaRoute
  '/maturacao': typeof MaturacaoRoute
  '/metodologia': typeof MetodologiaRoute
  '/mix': typeof MixRoute
  '/pracas': typeof PracasRoute
  '/qualidade': typeof QualidadeRoute
  '/simulador': typeof SimuladorRoute
  '/externos/abastecimento': typeof ExternosAbastecimentoRoute
  '/externos/aderencia': typeof ExternosAderenciaRoute
  '/externos/mercado': typeof ExternosMercadoRoute
  '/externos/operacao': typeof ExternosOperacaoRoute
  '/externos/risco': typeof ExternosRiscoRoute
  '/externos/': typeof ExternosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/financeiro': typeof FinanceiroRoute
  '/mapa': typeof MapaRoute
  '/maturacao': typeof MaturacaoRoute
  '/metodologia': typeof MetodologiaRoute
  '/mix': typeof MixRoute
  '/pracas': typeof PracasRoute
  '/qualidade': typeof QualidadeRoute
  '/simulador': typeof SimuladorRoute
  '/externos/abastecimento': typeof ExternosAbastecimentoRoute
  '/externos/aderencia': typeof ExternosAderenciaRoute
  '/externos/mercado': typeof ExternosMercadoRoute
  '/externos/operacao': typeof ExternosOperacaoRoute
  '/externos/risco': typeof ExternosRiscoRoute
  '/externos': typeof ExternosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/financeiro': typeof FinanceiroRoute
  '/mapa': typeof MapaRoute
  '/maturacao': typeof MaturacaoRoute
  '/metodologia': typeof MetodologiaRoute
  '/mix': typeof MixRoute
  '/pracas': typeof PracasRoute
  '/qualidade': typeof QualidadeRoute
  '/simulador': typeof SimuladorRoute
  '/externos/abastecimento': typeof ExternosAbastecimentoRoute
  '/externos/aderencia': typeof ExternosAderenciaRoute
  '/externos/mercado': typeof ExternosMercadoRoute
  '/externos/operacao': typeof ExternosOperacaoRoute
  '/externos/risco': typeof ExternosRiscoRoute
  '/externos/': typeof ExternosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carteira'
    | '/financeiro'
    | '/mapa'
    | '/maturacao'
    | '/metodologia'
    | '/mix'
    | '/pracas'
    | '/qualidade'
    | '/simulador'
    | '/externos/abastecimento'
    | '/externos/aderencia'
    | '/externos/mercado'
    | '/externos/operacao'
    | '/externos/risco'
    | '/externos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carteira'
    | '/financeiro'
    | '/mapa'
    | '/maturacao'
    | '/metodologia'
    | '/mix'
    | '/pracas'
    | '/qualidade'
    | '/simulador'
    | '/externos/abastecimento'
    | '/externos/aderencia'
    | '/externos/mercado'
    | '/externos/operacao'
    | '/externos/risco'
    | '/externos'
  id:
    | '__root__'
    | '/'
    | '/carteira'
    | '/financeiro'
    | '/mapa'
    | '/maturacao'
    | '/metodologia'
    | '/mix'
    | '/pracas'
    | '/qualidade'
    | '/simulador'
    | '/externos/abastecimento'
    | '/externos/aderencia'
    | '/externos/mercado'
    | '/externos/operacao'
    | '/externos/risco'
    | '/externos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarteiraRoute: typeof CarteiraRoute
  FinanceiroRoute: typeof FinanceiroRoute
  MapaRoute: typeof MapaRoute
  MaturacaoRoute: typeof MaturacaoRoute
  MetodologiaRoute: typeof MetodologiaRoute
  MixRoute: typeof MixRoute
  PracasRoute: typeof PracasRoute
  QualidadeRoute: typeof QualidadeRoute
  SimuladorRoute: typeof SimuladorRoute
  ExternosAbastecimentoRoute: typeof ExternosAbastecimentoRoute
  ExternosAderenciaRoute: typeof ExternosAderenciaRoute
  ExternosMercadoRoute: typeof ExternosMercadoRoute
  ExternosOperacaoRoute: typeof ExternosOperacaoRoute
  ExternosRiscoRoute: typeof ExternosRiscoRoute
  ExternosIndexRoute: typeof ExternosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maturacao': {
      id: '/maturacao'
      path: '/maturacao'
      fullPath: '/maturacao'
      preLoaderRoute: typeof MaturacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mix': {
      id: '/mix'
      path: '/mix'
      fullPath: '/mix'
      preLoaderRoute: typeof MixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pracas': {
      id: '/pracas'
      path: '/pracas'
      fullPath: '/pracas'
      preLoaderRoute: typeof PracasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualidade': {
      id: '/qualidade'
      path: '/qualidade'
      fullPath: '/qualidade'
      preLoaderRoute: typeof QualidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/externos/': {
      id: '/externos/'
      path: '/externos'
      fullPath: '/externos/'
      preLoaderRoute: typeof ExternosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/externos/abastecimento': {
      id: '/externos/abastecimento'
      path: '/externos/abastecimento'
      fullPath: '/externos/abastecimento'
      preLoaderRoute: typeof ExternosAbastecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/externos/aderencia': {
      id: '/externos/aderencia'
      path: '/externos/aderencia'
      fullPath: '/externos/aderencia'
      preLoaderRoute: typeof ExternosAderenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/externos/mercado': {
      id: '/externos/mercado'
      path: '/externos/mercado'
      fullPath: '/externos/mercado'
      preLoaderRoute: typeof ExternosMercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/externos/operacao': {
      id: '/externos/operacao'
      path: '/externos/operacao'
      fullPath: '/externos/operacao'
      preLoaderRoute: typeof ExternosOperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/externos/risco': {
      id: '/externos/risco'
      path: '/externos/risco'
      fullPath: '/externos/risco'
      preLoaderRoute: typeof ExternosRiscoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarteiraRoute: CarteiraRoute,
  FinanceiroRoute: FinanceiroRoute,
  MapaRoute: MapaRoute,
  MaturacaoRoute: MaturacaoRoute,
  MetodologiaRoute: MetodologiaRoute,
  MixRoute: MixRoute,
  PracasRoute: PracasRoute,
  QualidadeRoute: QualidadeRoute,
  SimuladorRoute: SimuladorRoute,
  ExternosAbastecimentoRoute: ExternosAbastecimentoRoute,
  ExternosAderenciaRoute: ExternosAderenciaRoute,
  ExternosMercadoRoute: ExternosMercadoRoute,
  ExternosOperacaoRoute: ExternosOperacaoRoute,
  ExternosRiscoRoute: ExternosRiscoRoute,
  ExternosIndexRoute: ExternosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
