// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// Falha em modo silencioso quando não há Supabase configurado (projeto de
// portfólio: o dashboard roda inteiro a partir de src/lib/novara/facts.ts,
// sem precisar de backend nenhum) — sem o try/catch, o simples fato de
// acessar `supabase.auth` já lançaria "Missing Supabase environment
// variable(s)" e derrubaria toda chamada de servidor.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    try {
      const { data } = await supabase.auth.getSession()
      const token = data.session?.access_token
      return next({
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      })
    } catch {
      return next({ headers: {} })
    }
  },
)
